### ISSUE TITLE
Not Responsive in Firefox 45.0.2

### ISSUE THREAD

**Issue by JackGraphix** [varunnaik/A-Slider#16]
Works well in Chrome and Safari, but images don't scale in FireFox.

**Comment by JackGraphix** [comment]
Easy fix. Changed "max-width" to "width". Seems to be working in FireFox now.

On the .HTML page:

 .aslide img {
               max-width: 100%;  
            }

.aslide img {
                width: 100%;  
            }

**Comment by varunnaik** [comment]
There doesn't seem to be a problem as far as I can tell - the slider is properly responsive on the latest Firefox and Chrome. I'm closing this issue for now, if this still not resolved please comment with a note on how to reproduce the problem.
